const LABELS = {
	RANDOM_CAFE: 'CAFE_RANDOM',
	LIST_ALL_CAFES: 'CAFE_LIST',
	SUGGEST_NEW_CAFE: 'CAFE_ADD',

	NEARBY_VICINITY: 'WITHIN_NEARBY',
	NEARBY_COUNTRY: 'WITHIN_COUNTRY'
};

module.exports = LABELS;