var Actions = {
	CAFE_RANDOM: 'CAFE_RANDOM',
	CAFE_LIST: 'CAFE_LIST',
	CAFE_ADD: 'CAFE_ADD',
	WITHIN_NEARBY_LIST: 'WITHIN_NEARBY_LIST',
	WITHIN_NEARBY_RANDOM: 'WITHIN_NEARBY_RANDOM',
	WITHIN_COUNTRY_RANDOM: 'WITHIN_COUNTRY_RANDOM',
	WITHIN_COUNTRY_RANDOM_REPEAT: 'WITHIN_COUNTRY_RANDOM_REPEAT'
};

module.exports = Actions;