var Actions = {
	CAFE_RANDOM: 'CAFE_RANDOM',
	CAFE_LIST: 'CAFE_LIST',
	CAFE_ADD: 'CAFE_ADD',
	WITHIN_200M_LIST: 'WITHIN_200M_LIST',
	WITHIN_200M_RANDOM: 'WITHIN_200M_RANDOM',
	WITHIN_COUNTRY_RANDOM: 'WITHIN_COUNTRY_RANDOM',
	WITHIN_COUNTRY_RANDOM_REPEAT: 'WITHIN_COUNTRY_RANDOM_REPEAT'
};

module.exports = Actions;