var Actions = {
	CAFE_RANDOM: 'CAFE_RANDOM',
	CAFE_LIST: 'CAFE_LIST',
	CAFE_ADD: 'CAFE_ADD',
	WITHIN_NEARBY: 'WITHIN_NEARBY',
	WITHIN_COUNTRY_RANDOM: 'WITHIN_COUNTRY_RANDOM'
};

module.exports = Actions;